server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1990
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialict: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hola
    password: hola

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000



